//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hastaneler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hastaneler()
        {
            this.Personellers = new HashSet<Personeller>();
        }
    
        public int HastaneID { get; set; }
        public string HastaneAdi { get; set; }
        public Nullable<int> AltBolgeID { get; set; }
        public string HastaneTel { get; set; }
        public string HastaneAdres { get; set; }
        public string HastaneMail { get; set; }
        public Nullable<bool> durum { get; set; }
    
        public virtual AltBolge AltBolge { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Personeller> Personellers { get; set; }
    }
}
