//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HastaTahlil
    {
        public int TahlilID { get; set; }
        public int HastaID { get; set; }
        public Nullable<System.DateTime> TahlilTarih { get; set; }
        public Nullable<System.DateTime> SonucTarih { get; set; }
        public string TahlilSonuc { get; set; }
    
        public virtual Hasta Hasta { get; set; }
        public virtual Tahliller Tahliller { get; set; }
    }
}
