//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Doktor
    {
        public int DoktorID { get; set; }
        public int TBID { get; set; }
        public string Doktor { get; set; }
        public string TibbiAdi { get; set; }
    }
}
